[project]
org-name = "acs"
version = "1.0.2"
authors = ["Abstract Concept Studios"]
keywords = ["MIME", "content", "type", "extension"]
repository = "https://github.com/Abstract-Concept-Studios/mimebyext"
